<a href="https://colab.research.google.com/github/aleksandrablaszczyk/bikes/blob/Data-Science-bootcamp/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import i sprawdzenie wersji
import numpy as np
np.__version__

'1.23.5'

In [2]:
#klasy, metody, atrybuty

print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [3]:
#podstawowa funkcja to array. Tutaj komenda, żeby wyświetlić dokumentację

help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

##1D Array

ważna jest umiejętność posługiwania się typami tablic. Dzięki temu możemy poprawnie wykonywać funkcje sieci neuronowych, które składają się z wielu operacji mnożenia i dodawania macierzy. Umiejętność dobrego operowania na kształtach jest kluczowa.

In [4]:
#Podstawowym obiektem Numpy jest wielowymiarowa tablica. Cechą charakterystyczną jest jednorodność elementów - ten sam typ. Wymiary często nazywane są osiami - axes. Klasa do której należą te obiekty to nD array
#na początek 1D array

x = np.array([1,3])
x
#x jest tablicą jednowymiarową. Można ją też wyprintować:

print(x)


[1 3]


In [5]:
#Możęmy sprawdzić typ tego obiektu.
type(x)

numpy.ndarray

In [6]:
#Teraz atrybuty klasy nD array

x.ndim

#mierzy wymiar tablicy

1

In [7]:
#kształt
x.shape

#często używany

(2,)

In [8]:
#liczba elementów w tablicy
x.size

2

In [9]:
#określa typ danych
x.dtype

#często używany

dtype('int64')

In [10]:
x= np.array ([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [11]:
x.dtype

dtype('float64')

# 2D array

In [12]:
x= np.array([[1,2,], [-3,1]])
x
#wyświetla się jako tablica dwucwymiarowa

array([[ 1,  2],
       [-3,  1]])

In [13]:
x.ndim

2

In [14]:
x.shape
#2 wiersze i 2 kolumny

(2, 2)

In [15]:
#tutaj robimy znowu dwuwierszową tablicę, ale z 3 kolumnami - widać w shape
x = np.array([[1,2,4], [4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [16]:
x.shape

(2, 3)

#3D Array

Marcierze trójwymiarowe pozwalają przechowywać bardziej skomplikowane rzeczy, jak np. obrazy

In [17]:
#tutaj trzeba bardzo uważnie z tym zagnieżdżaniem - wcale nie jest to takie oczywiste
x = np.array(
    [[[4,3,1],
      [3,1,2]],

      [[4,1,3],
       [4,2,1]],

     [[3,2,1],
      [4,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [18]:
#teraz powinno się wyświetlić 3
x.ndim

3

In [19]:
x.shape

(3, 2, 3)

wyświetla się 3,2,3 bo mamy:
* 3 tablice
* 2 wiersze
* 3 kolumny

#Typy danych

In [20]:
A = np.array([1,2,3])
A.dtype
#NumPy domyslnie wybiera najbardziej pasujący typ danych. W tym przypadku - liczb całkowitych - jest to int64

dtype('int64')

In [21]:
A = np.array([1.0,2.3,3.3])
A.dtype
#tutaj mamy ułamki, więc będzie to float64

dtype('float64')

In [22]:
#można też samodzielnie ustawić jaki to typ, wtedy mimo że są to liczby całkowite, będą one wyświetlone jako float64
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [23]:
A

array([1., 2., 3.])

In [24]:
A = np.array([1,2,3], dtype='complex')
A.dtype
#typ złożony - complex

dtype('complex128')

In [25]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [26]:
#teraz robimy odwrotnie. Float wyświetlamy jako integer. Trzeba tutaj bardzo uważać, ponieważ te wartości będą obcięte i wyświetlą tylko liczby całkowite
A = np.array([1.0,2.3,3.3], dtype='int')
A.dtype

dtype('int64')

In [27]:
A

array([1, 2, 3])

In [28]:
A = np.array ([True, False])
A.dtype

dtype('bool')

In [29]:
#można też używać mniejszego typu danych, przydaje się np. w analizie obrazów, ale ma ograniczenia do liczb całkowityh 8bitowych.
A = np.array([24,120,230], dtype=np.int8)
A.dtype

dtype('int8')

In [30]:
#dużo bardziej populerne jest użycie uint8, możemy wtedy użyć wartości od 0 do 255, czyli akurat żeby opisać obraz
A = np.array([24,120,230], dtype=np.uint8)
A.dtype

dtype('uint8')

#Tworzenie tablic

## Zeros

In [31]:
#Mamy kilka wbudowanych funkcji, które pozwalają lepiej budować tablice i automatyzować ten proces.

A = np.zeros(shape=(4,10))
A
#ta funkcja tworzy tablicę o podanym wymiarze z samych zer - tutaj 4 wiersze i 10 kolumn. Funkcja ta przydaje się do tworzenia masek w technikach computer vision, np jak mamy zdjęcie 600x800 pix, które ma czarne tło, wtedy się to przydaje


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
A.dtype

dtype('float64')

In [33]:
#domyślnym typem tutaj jest float, ale możemy sobie to ustawić

A = np.zeros(shape=(4,10), dtype='int')
A

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
A.dtype

dtype('int64')

## Ones

In [35]:
#Działa bardzo podobnie, ale stawia wszędzie jedynki

A= np.ones(shape=(5,5), dtype='int')
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

##Full

In [36]:
#Funkcja full działa na podobnej zasadzie, ale pozwala na wstawienie dowolnej wartości - nie tylko 0 i 1
A = np.full(shape=(3,3), fill_value=4, dtype='int')
A

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

## Arange

In [37]:
#pozwala wyświetlić dane w postaci np.array

np.arange(10)

#działa analogicznie do range w pythonie

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
#posiada też inne parametry - pozwala zmienić element od którego będziemy zaczynać, na którym kończyć i co ile ma iterować:

np.arange(start=10, stop=101, step=10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [39]:
#krok może mieć wartość ujemną:

np.arange(start=100, stop=9, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [40]:
#Step nie musi być int, może być ułamek
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

## Linspace

In [41]:
#przekazujemy start, stop i zamiast step mamy parametr "num", który mówi ile chcemy mieć liczb i one zostaną równo rozłożone

np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Zmienianie kształtu

In [42]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
#Aby zmienić rozmiar danych używamy reshape

A.reshape((3,5))
#wtedy tablica zmienia rozmiar na 3x5 zamiast jednowymiarowej

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
#Jak podamy -1 w liczbie kolumn, to python sam dopasuje tę liczbę - nie musimy tego liczyć, podajemy tylko liczbę wierszy w tej sytuacji
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
#można też odwrotnie:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

#Podstawowe opracje na tablicach

In [46]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [47]:
#Dodawanie - dodajemy element po elemencie
A + B

array([6, 0, 7, 4])

In [48]:
A - B

array([0, 2, 1, 0])

In [49]:
A* B

array([ 9, -1, 12,  4])

In [50]:
#Przy dzieleniu typ zostanie przekonwertowany na float
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [51]:
#są też metody numpy
np.add(A,B)

array([6, 0, 7, 4])

In [52]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [53]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [54]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [55]:
#dodawanie stałej do tablicy
A + 3

array([6, 4, 7, 5])

In [56]:
A * 2

array([6, 2, 8, 4])

In [57]:
#można też łączyć działania
A + 3*B

array([12, -2, 13,  8])

In [58]:
#Mnożenie macierzowe

In [59]:
X = np.array ([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [60]:
#daje to mnożenie po elemencie - 1*6=6 itd. Nie jest to jednak mnożenie jakie znamy z algebry liniowej, czyli mnożenie macierzy
X * Y

array([[6, 0],
       [2, 0]])

In [61]:
#Aby mnożyć macierze (czyli wiersz * kolumna, wiersz*kolumna):

np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

To było mało intuicyjne, więc wyjaśnienie dla mnie (z oznaczeniem z której tablicy biorę liczbę)

1. A1 *B6 + A3*B(-1)=3
2. A(-2)*B6 + A0*B(-1)=-12
3. A1*B0 + A3*B2 = 6
4. A(-2)*B0 + A0+B2 = 0

Czyli array:

[[3, 6]

[-12,0]]

In [62]:
#ten sam wynik dla macierzy
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [63]:
#Mnożenie macierzy nie jest zamienne! XY =! YX
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [64]:
# symbol @ też jest do mnożenia macierzowego

X @ Y

array([[  3,   6],
       [-12,   0]])

## Generowanie liczb pseudolosowych

In [65]:
#ustawienie ziarna losowania, żeby za każdym razem dostać to samo losowanie
np.random.seed(0)

In [66]:
#losowy rozkład normalny
np.random.randn()

1.764052345967664

In [67]:
#możemy podać parametr - wtedy dostaniemy tablicę zawierającą wskazaną liczbę elementów
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [68]:
#Można dodać też drugi parametr, wtedy dostaniemy tablicę 10(wiersze - próbki) x4 (kolumny)
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [69]:
#rozkład jednostajny na przedziale (czyli: ciągły rozkład prawdopodobieństwa, dla którego gęstość prawdopodobieństwa w przedziale od, a do b jest stała i różna od zera, a poza nim równa zeru.)
np.random.rand()

0.1965823616800535

In [70]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [71]:
np.random.rand(10,4)

array([[0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782]])

In [72]:
#zwróci całkowitą od 0 do wartości podanej
np.random.randint(10)

8

In [73]:
#tutaj mamy 2 dodatkowe parametry - parametr startowy, i parametr końcowy
np.random.randint(low=10, high=101)

26

In [74]:
#parametr size podaje ile wartosci zostanie zwróconych
np.random.randint(low=10, high=101, size=10)

array([34, 39, 31, 35, 90, 70, 71, 93, 43, 42])

In [75]:
#metoda random choice zwraca nam losowy element z listy
np.random.choice([4,2,1,5])

4

In [76]:
#zamiast wartości liczbowych, możemy mieć tekstowe
np.random.choice(['python', 'java', 'sql'])

'java'

In [77]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
#do tasowania danych - jako parametr te dane, które chcemy przetasować
np.random.shuffle(data)

In [79]:
data
#w numpy nie musimy przypisywać nowej zmiennej do takiego działania - w pandas trzeba

array([2, 4, 1, 3, 9, 0, 8, 7, 5, 6])

## Podstawowe funkcje

In [80]:
#eksponent - Zwraca wartość liczby e podniesioną do potęgi liczby. Stała e jest równa 2,71828182845904, podstawie logarytmu naturalnego. Wykorzystywane w sieciach neuronowych.

np.exp(1)

2.718281828459045

In [81]:
#zwraca pierwiastek kwadratowy, w formie float
np.sqrt(9)

3.0

In [82]:
#przechodzi po obiekcie iterowalnym i sprawdza czy każda wartość logiczna zwraca prawdę czy fałsz. Jeśli każdy obiekt zwraca prawdę, to zwróci prawdę
np.all([2,3,1])

True

In [83]:
np.all([2,3,0])

False

In [84]:
#sprawdza czy jakikolwiek obiekt jest prawdą
np.any([1,2,1])

True

In [85]:
np.any([0,0,0])

False

In [86]:
bool(0)

False

In [87]:
#sprawdzenie bool na wartości dowolnej innej niż 0 daje True
bool(1.2)

True

In [88]:
A = np.random.rand(5)
A

array([0.87845219, 0.10286336, 0.09237389, 0.35404666, 0.55181626])

In [89]:
#index gdzie nasza funkcja przyjmuje funkcję największą
np.argmax(A)

0

In [90]:
#Aby wskazać tę wartość
A[np.argmax(A)]

0.878452190276042

In [91]:
np.argmin(A)

2

In [92]:
A[np.argmin(A)]

0.0923738894608982

In [93]:
#argsort pokazuje nam kolejność indeksów od najmniejszej liczby
np.argsort(A)

array([2, 1, 3, 4, 0])

In [94]:
#max
np.max(A)

0.878452190276042

In [95]:
#min
np.min(A)

0.0923738894608982

In [96]:
#średnia
np.mean(A)

0.3959104719294896

In [97]:
#mediana
np.median(A)

0.3540466620838102

In [98]:
#odchylenie standardowe
np.std(A)

0.295606755834829

##Indeksowanie i wycinanie

In [100]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [101]:
#A[idx] - konkretny index który chcemy zwrócić,
#A[start:stop] - zakres od:do,
#A[:stop] - od 0 do wskazanego
#A[start:] - od wskazanego do końca

In [102]:
A[2]

2

In [103]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [105]:
A[:2] #ten elemenet nie wchodzi do listy

array([0, 1])

In [106]:
#możemy wyciąć konkretne indeksy poprzez listę
A[[0,2]]

array([0, 2])

In [107]:
#liczenie elementów od końca - podanie liczby ujemnej
A[-1]

19

In [108]:
A[10:15]

array([10, 11, 12, 13, 14])

In [110]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [111]:
#wycięcie całego pierwszego wiersza
A[0]

array([0, 1, 2, 3, 4])

In [112]:
A[1]

array([5, 6, 7, 8, 9])

In [114]:
#żeby zwrócić kolunę podajemy najpierw dwukropek przecinek a potem indeks kolumny
A[:, 0]

array([ 0,  5, 10, 15])

In [115]:
A[:,-1]

array([ 4,  9, 14, 19])

In [117]:
A[:,-2]

array([ 3,  8, 13, 18])

In [118]:
#konkretne położenie
A[1,1]

6

In [119]:
A[1,3]

8

In [121]:
#jeśli więcej wartości - nie konkretny wiersz i kolumna
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [125]:
#zmiana wartości w tablicy
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

##Iteracja po tablicach

In [126]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [127]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [129]:
#żeby wyprintować konkretną kolumę
for row in A:
  print(row[0])

0
5
10
15


In [130]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [131]:
for row in A:
  print(row[2:])

[2 3 4]
[14  8  9]
[12 13 14]
[17 18 19]


In [133]:
#żeby iterować po każdym elemencie
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


##Zmiana rozmiaru tablic

In [134]:
A.shape

(4, 5)

In [135]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [136]:
#wypłaszczenie danych
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [139]:
#rozumiem, że ravel jest prostsze, ale w sumie tak też działa
A.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [140]:
#transponowanie - zamieniamy wiersz na kolumnę
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

##Maski logiczne

In [141]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [144]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [146]:
#Maska logiczna na tablicę - zwraca prawdę lub fałsz
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [148]:
#Można zwrócić tam, gdzie jest to prawda
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [149]:
#Można też dla przedzału. Nie zadziała proste "AND"
np.bitwise_and(A> -5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [150]:
A[np.bitwise_and(A> -5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [151]:
A[np.bitwise_or(A<-5, A>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])

In [152]:
A[np.bitwise_xor(A<-5,A>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])