<a href="https://colab.research.google.com/github/aleksandrablaszczyk/bikes/blob/Data-Science-bootcamp/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#import i sprawdzenie wersji
import numpy as np
np.__version__

'1.23.5'

In [3]:
#klasy, metody, atrybuty

print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [4]:
#podstawowa funkcja to array. Tutaj komenda, żeby wyświetlić dokumentację

help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

##1D Array

ważna jest umiejętność posługiwania się typami tablic. Dzięki temu możemy poprawnie wykonywać funkcje sieci neuronowych, które składają się z wielu operacji mnożenia i dodawania macierzy. Umiejętność dobrego operowania na kształtach jest kluczowa.

In [5]:
#Podstawowym obiektem Numpy jest wielowymiarowa tablica. Cechą charakterystyczną jest jednorodność elementów - ten sam typ. Wymiary często nazywane są osiami - axes. Klasa do której należą te obiekty to nD array
#na początek 1D array

x = np.array([1,3])
x
#x jest tablicą jednowymiarową. Można ją też wyprintować:

print(x)


[1 3]


In [6]:
#Możęmy sprawdzić typ tego obiektu.
type(x)

numpy.ndarray

In [7]:
#Teraz atrybuty klasy nD array

x.ndim

#mierzy wymiar tablicy

1

In [8]:
#kształt
x.shape

#często używany

(2,)

In [9]:
#liczba elementów w tablicy
x.size

2

In [10]:
#określa typ danych
x.dtype

#często używany

dtype('int64')

In [11]:
x= np.array ([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [12]:
x.dtype

dtype('float64')

# 2D array

In [13]:
x= np.array([[1,2,], [-3,1]])
x
#wyświetla się jako tablica dwucwymiarowa

array([[ 1,  2],
       [-3,  1]])

In [14]:
x.ndim

2

In [15]:
x.shape
#2 wiersze i 2 kolumny

(2, 2)

In [16]:
#tutaj robimy znowu dwuwierszową tablicę, ale z 3 kolumnami - widać w shape
x = np.array([[1,2,4], [4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [17]:
x.shape

(2, 3)

#3D Array

Marcierze trójwymiarowe pozwalają przechowywać bardziej skomplikowane rzeczy, jak np. obrazy

In [18]:
#tutaj trzeba bardzo uważnie z tym zagnieżdżaniem - wcale nie jest to takie oczywiste
x = np.array(
    [[[4,3,1],
      [3,1,2]],

      [[4,1,3],
       [4,2,1]],

     [[3,2,1],
      [4,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [19]:
#teraz powinno się wyświetlić 3
x.ndim

3

In [20]:
x.shape

(3, 2, 3)

wyświetla się 3,2,3 bo mamy:
* 3 tablice
* 2 wiersze
* 3 kolumny

#Typy danych

In [21]:
A = np.array([1,2,3])
A.dtype
#NumPy domyslnie wybiera najbardziej pasujący typ danych. W tym przypadku - liczb całkowitych - jest to int64

dtype('int64')

In [22]:
A = np.array([1.0,2.3,3.3])
A.dtype
#tutaj mamy ułamki, więc będzie to float64

dtype('float64')

In [23]:
#można też samodzielnie ustawić jaki to typ, wtedy mimo że są to liczby całkowite, będą one wyświetlone jako float64
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [24]:
A

array([1., 2., 3.])

In [25]:
A = np.array([1,2,3], dtype='complex')
A.dtype
#typ złożony - complex

dtype('complex128')

In [26]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [27]:
#teraz robimy odwrotnie. Float wyświetlamy jako integer. Trzeba tutaj bardzo uważać, ponieważ te wartości będą obcięte i wyświetlą tylko liczby całkowite
A = np.array([1.0,2.3,3.3], dtype='int')
A.dtype

dtype('int64')

In [28]:
A

array([1, 2, 3])

In [29]:
A = np.array ([True, False])
A.dtype

dtype('bool')

In [30]:
#można też używać mniejszego typu danych, przydaje się np. w analizie obrazów, ale ma ograniczenia do liczb całkowityh 8bitowych.
A = np.array([24,120,230], dtype=np.int8)
A.dtype

dtype('int8')

In [31]:
#dużo bardziej populerne jest użycie uint8, możemy wtedy użyć wartości od 0 do 255, czyli akurat żeby opisać obraz
A = np.array([24,120,230], dtype=np.uint8)
A.dtype

dtype('uint8')

#Tworzenie tablic

## Zeros

In [32]:
#Mamy kilka wbudowanych funkcji, które pozwalają lepiej budować tablice i automatyzować ten proces.

A = np.zeros(shape=(4,10))
A
#ta funkcja tworzy tablicę o podanym wymiarze z samych zer - tutaj 4 wiersze i 10 kolumn. Funkcja ta przydaje się do tworzenia masek w technikach computer vision, np jak mamy zdjęcie 600x800 pix, które ma czarne tło, wtedy się to przydaje


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
A.dtype

dtype('float64')

In [34]:
#domyślnym typem tutaj jest float, ale możemy sobie to ustawić

A = np.zeros(shape=(4,10), dtype='int')
A

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
A.dtype

dtype('int64')

## Ones

In [36]:
#Działa bardzo podobnie, ale stawia wszędzie jedynki

A= np.ones(shape=(5,5), dtype='int')
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

##Full

In [37]:
#Funkcja full działa na podobnej zasadzie, ale pozwala na wstawienie dowolnej wartości - nie tylko 0 i 1
A = np.full(shape=(3,3), fill_value=4, dtype='int')
A

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

## Arange

In [38]:
#pozwala wyświetlić dane w postaci np.array

np.arange(10)

#działa analogicznie do range w pythonie

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#posiada też inne parametry - pozwala zmienić element od którego będziemy zaczynać, na którym kończyć i co ile ma iterować:

np.arange(start=10, stop=101, step=10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [40]:
#krok może mieć wartość ujemną:

np.arange(start=100, stop=9, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [41]:
#Step nie musi być int, może być ułamek
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

## Linspace

In [42]:
#przekazujemy start, stop i zamiast step mamy parametr "num", który mówi ile chcemy mieć liczb i one zostaną równo rozłożone

np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Zmienianie kształtu

In [43]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
#Aby zmienić rozmiar danych używamy reshape

A.reshape((3,5))
#wtedy tablica zmienia rozmiar na 3x5 zamiast jednowymiarowej

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
#Jak podamy -1 w liczbie kolumn, to python sam dopasuje tę liczbę - nie musimy tego liczyć, podajemy tylko liczbę wierszy w tej sytuacji
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
#można też odwrotnie:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

#Podstawowe opracje na tablicach

In [47]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [48]:
#Dodawanie - dodajemy element po elemencie
A + B

array([6, 0, 7, 4])

In [49]:
A - B

array([0, 2, 1, 0])

In [50]:
A* B

array([ 9, -1, 12,  4])

In [51]:
#Przy dzieleniu typ zostanie przekonwertowany na float
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [52]:
#są też metody numpy
np.add(A,B)

array([6, 0, 7, 4])

In [53]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [54]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [55]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [56]:
#dodawanie stałej do tablicy
A + 3

array([6, 4, 7, 5])

In [57]:
A * 2

array([6, 2, 8, 4])

In [58]:
#można też łączyć działania
A + 3*B

array([12, -2, 13,  8])

In [59]:
#Mnożenie macierzowe

In [60]:
X = np.array ([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [62]:
#daje to mnożenie po elemencie - 1*6=6 itd. Nie jest to jednak mnożenie jakie znamy z algebry liniowej, czyli mnożenie macierzy
X * Y

array([[6, 0],
       [2, 0]])

In [63]:
#Aby mnożyć macierze (czyli wiersz * kolumna, wiersz*kolumna):

np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

To było mało intuicyjne, więc wyjaśnienie dla mnie (z oznaczeniem z której tablicy biorę liczbę)

1. A1 *B6 + A3*B(-1)=3
2. A(-2)*B6 + A0*B(-1)=-12
3. A1*B0 + A3*B2 = 6
4. A(-2)*B0 + A0+B2 = 0

Czyli array:

[[3, 6]

[-12,0]]

In [64]:
#ten sam wynik dla macierzy
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [65]:
#Mnożenie macierzy nie jest zamienne! XY =! YX
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [66]:
# symbol @ też jest do mnożenia macierzowego

X @ Y

array([[  3,   6],
       [-12,   0]])

## Generowanie liczb pseudolosowych

In [67]:
#ustawienie ziarna losowania, żeby za każdym razem dostać to samo losowanie
np.random.seed(0)

In [68]:
#losowy rozkład normalny
np.random.randn()

1.764052345967664

In [69]:
#możemy podać parametr - wtedy dostaniemy tablicę zawierającą wskazaną liczbę elementów
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [71]:
#Można dodać też drugi parametr, wtedy dostaniemy tablicę 10(wiersze - próbki) x4 (kolumny)
np.random.randn(10,4)

array([[ 0.3869025 , -0.51080514, -1.18063218, -0.02818223],
       [ 0.42833187,  0.06651722,  0.3024719 , -0.63432209],
       [-0.36274117, -0.67246045, -0.35955316, -0.81314628],
       [-1.7262826 ,  0.17742614, -0.40178094, -1.63019835],
       [ 0.46278226, -0.90729836,  0.0519454 ,  0.72909056],
       [ 0.12898291,  1.13940068, -1.23482582,  0.40234164],
       [-0.68481009, -0.87079715, -0.57884966, -0.31155253],
       [ 0.05616534, -1.16514984,  0.90082649,  0.46566244],
       [-1.53624369,  1.48825219,  1.89588918,  1.17877957],
       [-0.17992484, -1.07075262,  1.05445173, -0.40317695]])

In [72]:
#rozkład jednostajny na przedziale (czyli: ciągły rozkład prawdopodobieństwa, dla którego gęstość prawdopodobieństwa w przedziale od, a do b jest stała i różna od zera, a poza nim równa zeru.)
np.random.rand()

0.8811031971111616

In [73]:
np.random.rand(10)

array([0.58127287, 0.88173536, 0.69253159, 0.72525428, 0.50132438,
       0.95608363, 0.6439902 , 0.42385505, 0.60639321, 0.0191932 ])

In [74]:
np.random.rand(10,4)

array([[0.30157482, 0.66017354, 0.29007761, 0.61801543],
       [0.4287687 , 0.13547406, 0.29828233, 0.56996491],
       [0.59087276, 0.57432525, 0.65320082, 0.65210327],
       [0.43141844, 0.8965466 , 0.36756187, 0.43586493],
       [0.89192336, 0.80619399, 0.70388858, 0.10022689],
       [0.91948261, 0.7142413 , 0.99884701, 0.1494483 ],
       [0.86812606, 0.16249293, 0.61555956, 0.12381998],
       [0.84800823, 0.80731896, 0.56910074, 0.4071833 ],
       [0.069167  , 0.69742877, 0.45354268, 0.7220556 ],
       [0.86638233, 0.97552151, 0.85580334, 0.01171408]])

In [76]:
#zwróci całkowitą od 0 do wartości podanej
np.random.randint(10)

5

In [77]:
#tutaj mamy 2 dodatkowe parametry - parametr startowy, i parametr końcowy
np.random.randint(low=10, high=101)

54

In [78]:
#parametr size podaje ile wartosci zostanie zwróconych
np.random.randint(low=10, high=101, size=10)

array([44, 44, 98, 43, 15, 46, 10, 85, 44, 79])

In [82]:
#metoda random choice zwraca nam losowy element z listy
np.random.choice([4,2,1,5])

2

In [83]:
#zamiast wartości liczbowych, możemy mieć tekstowe
np.random.choice(['python', 'java', 'sql'])

'java'

In [85]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
#do tasowania danych - jako parametr te dane, które chcemy przetasować
np.random.shuffle(data)

In [90]:
data
#w numpy nie musimy przypisywać nowej zmiennej do takiego działania - w pandas trzeba

array([9, 7, 2, 8, 5, 0, 6, 3, 4, 1])

## Podstawowe funkcje

In [91]:
#eksponent - Zwraca wartość liczby e podniesioną do potęgi liczby. Stała e jest równa 2,71828182845904, podstawie logarytmu naturalnego. Wykorzystywane w sieciach neuronowych.

np.exp(1)

2.718281828459045

In [92]:
#zwraca pierwiastek kwadratowy, w formie float
np.sqrt(9)

3.0

In [93]:
#przechodzi po obiekcie iterowalnym i sprawdza czy każda wartość logiczna zwraca prawdę czy fałsz. Jeśli każdy obiekt zwraca prawdę, to zwróci prawdę
np.all([2,3,1])

True

In [94]:
np.all([2,3,0])

False

In [95]:
#sprawdza czy jakikolwiek obiekt jest prawdą
np.any([1,2,1])

True

In [96]:
np.any([0,0,0])

False

In [97]:
bool(0)

False

In [101]:
#sprawdzenie bool na wartości dowolnej innej niż 0 daje True
bool(1.2)

True

In [100]:
A = np.random.rand(5)
A

array([0.21874937, 0.56957353, 0.45210904, 0.97023668, 0.68054469])

In [102]:
#index gdzie nasza funkcja przyjmuje funkcję największą
np.argmax(A)

3

In [103]:
#Aby wskazać tę wartość
A[np.argmax(A)]

0.9702366830961006

In [104]:
np.argmin(A)

0

In [105]:
A[np.argmin(A)]

0.21874937373677183

In [107]:
#argsort pokazuje nam kolejność indeksów od najmniejszej liczby
np.argsort(A)

array([0, 2, 1, 4, 3])

In [108]:
#max
np.max(A)

0.9702366830961006

In [109]:
#min
np.min(A)

0.21874937373677183

In [110]:
#średnia
np.mean(A)

0.5782426635267631

In [111]:
#mediana
np.median(A)

0.569573534574738

In [112]:
#odchylenie standardowe
np.std(A)

0.24873491418794316