<a href="https://colab.research.google.com/github/aleksandrablaszczyk/bikes/blob/Data-Science-bootcamp/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#import i sprawdzenie wersji
import numpy as np
np.__version__

'1.23.5'

In [ ]:
#klasy, metody, atrybuty

print(dir(np))

In [ ]:
#podstawowa funkcja to array. Tutaj komenda, żeby wyświetlić dokumentację

help(np.array)

##1D Array

ważna jest umiejętność posługiwania się typami tablic. Dzięki temu możemy poprawnie wykonywać funkcje sieci neuronowych, które składają się z wielu operacji mnożenia i dodawania macierzy. Umiejętność dobrego operowania na kształtach jest kluczowa.

In [9]:
#Podstawowym obiektem Numpy jest wielowymiarowa tablica. Cechą charakterystyczną jest jednorodność elementów - ten sam typ. Wymiary często nazywane są osiami - axes. Klasa do której należą te obiekty to nD array
#na początek 1D array

x = np.array([1,3])
x
#x jest tablicą jednowymiarową. Można ją też wyprintować:

print(x)


[1 3]


In [11]:
#Możęmy sprawdzić typ tego obiektu.
type(x)

numpy.ndarray

In [12]:
#Teraz atrybuty klasy nD array

x.ndim

#mierzy wymiar tablicy

1

In [16]:
#kształt
x.shape

#często używany

(2,)

In [14]:
#liczba elementów w tablicy
x.size

2

In [17]:
#określa typ danych
x.dtype

#często używany

dtype('int64')

In [19]:
x= np.array ([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [20]:
x.dtype

dtype('float64')

# 2D array

In [22]:
x= np.array([[1,2,], [-3,1]])
x
#wyświetla się jako tablica dwucwymiarowa

array([[ 1,  2],
       [-3,  1]])

In [23]:
x.ndim

2

In [25]:
x.shape
#2 wiersze i 2 kolumny

(2, 2)

In [30]:
#tutaj robimy znowu dwuwierszową tablicę, ale z 3 kolumnami - widać w shape
x = np.array([[1,2,4], [4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [29]:
x.shape

(2, 3)

#3D Array

Marcierze trójwymiarowe pozwalają przechowywać bardziej skomplikowane rzeczy, jak np. obrazy

In [41]:
#tutaj trzeba bardzo uważnie z tym zagnieżdżaniem - wcale nie jest to takie oczywiste
x = np.array(
    [[[4,3,1],
      [3,1,2]],

      [[4,1,3],
       [4,2,1]],

     [[3,2,1],
      [4,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [42]:
#teraz powinno się wyświetlić 3
x.ndim

3

In [43]:
x.shape

(3, 2, 3)

wyświetla się 3,2,3 bo mamy:
* 3 tablice
* 2 wiersze
* 3 kolumny

#Typy danych

In [48]:
A = np.array([1,2,3])
A.dtype
#NumPy domyslnie wybiera najbardziej pasujący typ danych. W tym przypadku - liczb całkowitych - jest to int64

dtype('int64')

In [49]:
A = np.array([1.0,2.3,3.3])
A.dtype
#tutaj mamy ułamki, więc będzie to float64

dtype('float64')

In [50]:
#można też samodzielnie ustawić jaki to typ, wtedy mimo że są to liczby całkowite, będą one wyświetlone jako float64
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [51]:
A

array([1., 2., 3.])

In [53]:
A = np.array([1,2,3], dtype='complex')
A.dtype
#typ złożony - complex

dtype('complex128')

In [54]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [55]:
#teraz robimy odwrotnie. Float wyświetlamy jako integer. Trzeba tutaj bardzo uważać, ponieważ te wartości będą obcięte i wyświetlą tylko liczby całkowite
A = np.array([1.0,2.3,3.3], dtype='int')
A.dtype

dtype('int64')

In [56]:
A

array([1, 2, 3])

In [57]:
A = np.array ([True, False])
A.dtype

dtype('bool')

In [59]:
#można też używać mniejszego typu danych, przydaje się np. w analizie obrazów, ale ma ograniczenia do liczb całkowityh 8bitowych.
A = np.array([24,120,230], dtype=np.int8)
A.dtype

dtype('int8')

In [60]:
#dużo bardziej populerne jest użycie uint8, możemy wtedy użyć wartości od 0 do 255, czyli akurat żeby opisać obraz
A = np.array([24,120,230], dtype=np.uint8)
A.dtype

dtype('uint8')

#Tworzenie tablic

## Zeros

In [69]:
#Mamy kilka wbudowanych funkcji, które pozwalają lepiej budować tablice i automatyzować ten proces.

A = np.zeros(shape=(4,10))
A
#ta funkcja tworzy tablicę o podanym wymiarze z samych zer - tutaj 4 wiersze i 10 kolumn. Funkcja ta przydaje się do tworzenia masek w technikach computer vision, np jak mamy zdjęcie 600x800 pix, które ma czarne tło, wtedy się to przydaje


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [70]:
A.dtype

dtype('float64')

In [71]:
#domyślnym typem tutaj jest float, ale możemy sobie to ustawić

A = np.zeros(shape=(4,10), dtype='int')
A

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [72]:
A.dtype

dtype('int64')

## Ones

In [74]:
#Działa bardzo podobnie, ale stawia wszędzie jedynki

A= np.ones(shape=(5,5), dtype='int')
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

##Full

In [78]:
#Funkcja full działa na podobnej zasadzie, ale pozwala na wstawienie dowolnej wartości - nie tylko 0 i 1
A = np.full(shape=(3,3), fill_value=4, dtype='int')
A

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

## Arange

In [81]:
#pozwala wyświetlić dane w postaci np.array

np.arange(10)

#działa analogicznie do range w pythonie

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
#posiada też inne parametry - pozwala zmienić element od którego będziemy zaczynać, na którym kończyć i co ile ma iterować:

np.arange(start=10, stop=101, step=10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [85]:
#krok może mieć wartość ujemną:

np.arange(start=100, stop=9, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [87]:
#Step nie musi być int, może być ułamek
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

## Linspace

In [89]:
#przekazujemy start, stop i zamiast step mamy parametr "num", który mówi ile chcemy mieć liczb i one zostaną równo rozłożone

np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Zmienianie kształtu

In [90]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
#Aby zmienić rozmiar danych używamy reshape

A.reshape((3,5))
#wtedy tablica zmienia rozmiar na 3x5 zamiast jednowymiarowej

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [94]:
#Jak podamy -1 w liczbie kolumn, to python sam dopasuje tę liczbę - nie musimy tego liczyć, podajemy tylko liczbę wierszy w tej sytuacji
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [95]:
#można też odwrotnie:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

#Podstawowe opracje na tablicach